version: '3.8'

services:
  web:
    build:
      context: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
    networks:
      - kami-network

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev 
    ports:
      - 5432:5432
    networks:
      - kami-network
volumes:
  postgres_data:

networks:
  kami-network:
    name: kami-network
