# Generated by Django 4.0.10 on 2023-12-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('airplane_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('passengers', models.PositiveIntegerField(verbose_name='number of passengers')),
            ],
        ),
    ]
